name: GitHub Actions Test
on: 
        push:
                branches:
                        -'master'

jobs:
        github-actions-test:
                steps:
                   -
                        name: Set up QEMU
                        uses: docker/setup-wemu-action@v1
                   -
                        name: Set up Docker Buildx
                        uses: docker/setup-buildx-action@v1
                   -
                        name: Login to DockerHub
                        uses: docker/login-action@v1
                        with:
                                username: ${{ secrets.DOCKERHUB_USERNAME }}
                                password: ${{ secerts.DOCKERHUB_TOKEN }}
                   -
                        name: Build and push
                        id: docker_build
                        uses: docker/build-push-action@v2
                        with:
                                context: .
                                push: true
                                platforms:linux/amd64,linux/arm64
                                tags: shoycha/python-helloworld:latest
                        
